FROM hseeberger/scala-sbt:11.0.8_1.4.1_2.12.12
MAINTAINER Samuel Tardieu, sam@rfc1149.net

# Set Java options to be more lenient with certificates
ENV JAVA_OPTS="-Djdk.tls.client.protocols=TLSv1.2"

ADD build.sbt /workspace/
ADD src /workspace/src/
ADD thirdparty /workspace/thirdparty
ADD project/build.properties project/plugins.sbt /workspace/project/
RUN cd /workspace && sbt assembly genCommands

FROM openjdk:26-ea-oracle
COPY --from=0 /workspace/ausweis.jar .
COPY --from=0 /workspace/commands.txt .
ADD start-with-env.sh ./
CMD ["./start-with-env.sh"]
ENV TZ=Europe/Paris
