:icons: font
ifdef::env-github[]
:lang: fr
:tip-caption: :bulb:
:important-caption: :heavy_exclamation_mark:
endif::[]

== Présentation générale

AusweisBot est un logiciel libre permettant de générer pendant la
pandémie de covid-19 une attestation dérogatoire de déplacement en
France à travers le réseau de communication
https://telegram.org[Telegram]. Une instance publique, utilisable par
tous, est disponible sur Telegram sous le nom
https://telegram.me/AusweisBot[@AusweisBot].

TIP: https://telegram.me/AusweisBot[Accédez à l’instance publique
@AusweisBot en cliquant ici]

AusweisBot est écrit en https://www.scala-lang.org/[Scala] et utilise
notamment l’intergiciel https://akka.io[Akka], la bibliothèque
https://github.com/bot4s/telegram[bots4s.telegram], la bibliothèque
https://pdfbox.apache.org/[Apache PDFBox] et la bibliothèque
https://github.com/zxing/zxing[ZXing]. Vous pouvez utiliser le
gestionnaire de tickets et de _pull requests_ de GitHub pour faire des
remarques sur des fonctionnalités ou proposer des changements.

== FAQ

=== Est-ce que AusweisBot stocke des données à caractère personnel ?

AusweisBot conserve les seules données strictement nécessaires à la
génération des attestations dérogatoires de sortie. Les données stockées
peuvent être consultées à tout moment en utilisant la commande `/data`
et effacées avec la commande `/start`.

Cette politique de gestion des données est détaillée dans le résultat de
la commande `/privacy` qui peut être utilisée à tout moment, notamment
avant la collecte des données personnelles.

=== Pourquoi ce nom ?

[quote, Emmanuel Macron, 16 mars 2020]
Nous sommes en guerre

« _Ausweis_ » est un mot allemand signifiant « pièce d’identité ». Il
était utilisé lors de la dernière guerre mondiale pour désigner les
laissez-passer dérogatoires dont la présentation était obligatoire pour
pouvoir circuler. Et puis cela permet de court-circuiter la
https://fr.wikipedia.org/wiki/Loi_de_Godwin[loi de Godwin] avant même de
commencer la discussion.

=== Quelles garanties apportez-vous ?

Pour être clair : _aucune_. Ce logiciel ainsi que le service en ligne
associé ont pour but de faciliter, sous votre propre responsabilité, la
création d’une attestation dérogatoire de déplacement conforme à ce
qu’exige la réglementation.

C’est à vous de vous assurer que les
informations qui figurent sur le document sont exactes. Le plus grand
soin a également été apporté au contenu du QR-code contenu dans
l’attestation afin de permettre une lecture sans contact du document par
les forces de l’ordre afin de préserver la santé de chacun, mais là
aussi, l’utilisation du QR-code lors d’un contrôle se fait sous la seule
responsabilité de l’utilisateur.

=== AusweisBot est-il utilisable dans les territoires d’outre-mer ?

AusweisBot est avant tout destiné à la France métropolitaine : Telegram
ne fournit aucune information sur la localisation de l’utilisateur ou le
fuseau horaire dans lequel il se trouve. On suppose donc que
l’utilisateur se trouve, par défaut, en France métropolitaine.

Cela n’empêche pas d’utiliser AusweisBot depuis les territoires
d’outre-mer en spécifiant un horaire explicite. Toutefois, une attention
particulière devra être apportée à l’examen du document produit pour
s’assurer que tout est en ordre.

=== Cela permet-il de sortir dans plus de cas ou plus souvent ?

Non, AusweisBot permet simplement de générer les attestations
dérogatoires de déplacement tel que vous le feriez avec l’attestation
papier ou le générateur d’attestation mis à disposition par le ministère
de l’intérieur. *Restez chez vous !*

=== Puis-je déployer mon propre bot à partir du code source de AusweisBot sur Telegram ?

Bien entendu, du moment que vous respectez les termes des licenses des
logiciels et données utilisés (cf. ci-dessous). De plus, vous devez vous
assurer que les informations permettant de vous contacter sont à jour.

=== Que pensez-vous du principe de cette attestation dérogatoire de déplacement ?

Peu importe ce que j’en pense, la présentation d’un document attestant
d’une raison valable de sortie est rendue obligatoire par l’article 3 du
https://www.legifrance.gouv.fr/affichTexte.do?cidTexte=JORFTEXT000041746694[décret
n° 2020-293 du 23 mars 2020]. Pour limiter les contacts lors du
contrôle, il me semble plus simple de présenter une attestation
identique à ce que propose le service en ligne du ministère de
l’intérieur en y incluant un QR-code incorporant le même contenu.

=== Pourquoi Scala et pas rust, elixir, etc. ?

La bibliothèque https://pdfbox.apache.org[Apache PDFBox] écrite pour
Java (et donc disponible directement en Scala) permet une manipulation
facile du fichier PDF contenant l’attestation. De plus,
https://akka.io[Akka] facilite la supervision et la reprise sur faute,
notamment en cas de défaillance temporaire des serveurs Telegram ou en
cas de perte de connectivité de l’ordinateur sur lequel le service est
hébergé.

=== Pourquoi Scala 2.12 et pas Scala 2.13 ?

La bibliothèque https://github.com/bot4s/telegram[bots4s.telegram] n’est
pas à ce jour disponible pour Scala 2.13 car elle utilise une dépendance
(`slogging`) qui n’est plus maintenue et n’a jamais été adaptée pour
Scala 2.13.

== Licence

IMPORTANT: AusweisBot est distribué sous les termes de la licence
https://www.gnu.org/licenses/agpl-3.0.html[GNU Affero Public License
version 3.0].

Pour faciliter la saisie du lieu de confinement, ce logiciel utilise une
liste des communes de France et de leurs codes postaux qui s’accompagne
de la licence suivante :

____
Ce(tte) œuvre de https://sql.sh est mise à disposition selon les termes
de la http://creativecommons.org/licenses/by-sa/4.0/[licence Creative
Commons Attribution – Partage dans les Mêmes Conditions 4.0
International].

Vous êtes libre de partager, distribuer ou utiliser cette base de
données, pour des utilisations commerciales ou non, à condition de
conserver cette licence et d’attribuer un lien vers le site sql.sh.
____

=== Comment lancer mon propre bot ?

Vous aurez besoin d’un ordinateur avec une connectivité permanente à
Telegram pour faire tourner votre version du bot. Il vous faudra
également créer un jeton d’authentification du bot auprès du
https://telegram.me/BotFather[gestionnaire de robots BotFather].

==== À la main

Vous aurez besoin de https://www.scala-sbt.org[`sbt`] pour compiler et
lancer ce programme.

Le fichier de configuration se trouve dans
`src/main/resources/application.conf`. Il vous faudra _a minima_ remplir
l’entrée `ausweis.telegram-token` avec le jeton d’authentification
fourni par BotFather et `ausweis.contact-email` avec votre adresse mail
de contact pour la gestion des données personnelles. Vous pouvez
préférer placer ces informations dans un fichier à la racine de votre
dépôt et le passer en premier argument du programme.

Par défaut, le programme se connecte à une base de données
https://couchdb.apache.org[CouchDB] tournant localement sur le port par
défaut.

Vous pouvez lancer le bot avec la commande `run` (ou
`run configuration-file`) de `sbt`.

==== Dans des conteneurs

Un fichier de configuration pour
https://docs.docker.com/compose/[docker-compose] est fourni à la racine
du dépôt, auquel cas seuls `docker` et `docker-compose` sont strictement
nécessaires.

Pour lancer votre instance du bot, il vous faut d’abord créer un fichier
de configuration `.env` à la racine du dépôt contenant _a minima_
`TELEGRAM_TOKEN=le-token-donné-par-BotFather` et
`CONTACT_EMAIL=votre-adresse-mail-de-contact`. Vous pouvez ensuite
générer les conteneurs avec `docker-compose build` puis les lancer avec
`docker-compose up`.
