before_install:
- sudo curl -L -o /usr/local/bin/mill https://github.com/lihaoyi/mill/releases/download/0.5.0/0.5.0 && sudo chmod +x /usr/local/bin/mill

language: scala

scala:
  - 2.11.12
  - 2.12.10

jdk:
  - openjdk8

script:  
  - mill "__.compile"
  - mill "__.test"
