name: tests
on:
  push:
    branches:
      - staging
      - trying
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get Ivy2 cache
        uses: actions/cache@v2
        with:
          path: ~/.ivy2
          key: ivy2-files
      - name: Checkout
        uses: actions/checkout@v2
      - name: SBT test
        id: sbt_test
        uses: lokkju/github-action-sbt@master
        with:
          commands: test
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker build
        id: docker_build
        uses: docker/build-push-action@v2
