name: Validation process
on:
  pull_request:
  merge_group:
jobs:
  test:
    name: Unit and building tests
    runs-on: ubuntu-latest
    steps:
      - name: Get Ivy2 cache
        uses: actions/cache@v3
        with:
          path: ~/.ivy2
          key: ivy2-files
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup Scala
        uses: olafurpg/setup-scala@v11
        with:
          java-version: "adopt@1.11"
      - name: Coursier cache
        uses: coursier/cache-action@v6
      - name: SBT tests and artifacts
        run: sbt test assembly genCommands
      - name: Upload ausweis.jar artifact
        uses: actions/upload-artifact@v3
        with:
          name: ausweis.jar
          path: ausweis.jar
      - name: Upload commands.txt artifact
        uses: actions/upload-artifact@v3
        with:
          name: commands.txt
          path: commands.txt
  package:
    name: Docker packaging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Docker build
        uses: docker/build-push-action@v2
