name: Validation process
on:
  push:
    branches:
      - staging
      - trying
jobs:
  test:
    name: Unit and building tests
    runs-on: ubuntu-latest
    steps:
      - name: Get Ivy2 cache
        uses: actions/cache@v2
        with:
          path: ~/.ivy2
          key: ivy2-files
      - name: Checkout
        uses: actions/checkout@v2
      - name: SBT tests and artifacts
        uses: lokkju/github-action-sbt@master
        with:
          commands: test assembly genCommands
      - name: Upload ausweis.jar artifact
        uses: actions/upload-artifact@v2
        with:
          name: ausweis.jar
          path: ausweis.jar
      - name: Upload commands.txt artifact
        uses: actions/upload-artifact@v2
        with:
          name: commands.txt
          path: commands.txt
  package:
    name: Docker packaging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker build
        uses: docker/build-push-action@v2
